const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const version = require('../package.json').version;
const output = path.join(root, 'artifacts', 'preview');
fs.mkdirSync(output, {recursive: true});
for (const name of ['index.html', 'demo.js', 'responsive.html']) fs.copyFileSync(path.join(root, 'preview', name), path.join(output, name));
const engine = fs.readFileSync(path.join(root, 'delete-tweets.js'), 'utf8');
const invocation = "})(typeof window==='undefined'?{}:window);";
if (!engine.includes(invocation)) throw Error('Demo entry point not found.');
fs.writeFileSync(path.join(output, 'cleaner.js'), engine.replace(invocation, '})(window.TweetCleanerDemoRoot);'));
const popupDir=path.join(output,'popup');
fs.mkdirSync(path.join(popupDir,'icons'),{recursive:true});
fs.copyFileSync(path.join(root,'extension/popup.css'),path.join(popupDir,'popup.css'));
for(const name of ['popup.js','messages.js','privacy.html','privacy-pt.html'])fs.copyFileSync(path.join(root,'extension',name),path.join(popupDir,name));
fs.copyFileSync(path.join(root,'extension/icons/48.png'),path.join(popupDir,'icons/48.png'));
const popup=fs.readFileSync(path.join(root,'extension/popup.html'),'utf8');
fs.writeFileSync(path.join(popupDir,'index.html'),popup.replace('<script src="popup.js">','<script src="stub.js"></script><script src="popup.js">'));
fs.writeFileSync(path.join(popupDir,'stub.js'),`const demoPreferences={},demoListeners=[];window.chrome={storage:{local:{get:async()=>demoPreferences,set:async values=>{Object.assign(demoPreferences,values);demoListeners.forEach(fn=>fn(Object.fromEntries(Object.entries(values).map(([key,value])=>[key,{newValue:value}])),'local'));}},onChanged:{addListener:fn=>demoListeners.push(fn)}},runtime:{getManifest:()=>({version:'${version}'})},tabs:{query:async()=>[{id:1,url:'https://x.com/sample_user'}]},scripting:{executeScript:async()=>[{result:{error:'Local demo. Install the extension to open the panel on X.'}}]}};`);
console.log('Local demo generated in artifacts/preview (excluded from ZIP).');
